n = input('Digite algo:')

print('O tipo primitivo desse valor é:',type(n))
print('Só têm espaços?',n.isspace())
print('É um número?',n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?',n.isalnum())
print('Está em maiúsculas?', n.isupper())
print('Ésta em minúsculas?', n.islower())
print('Está capitalizada?',n.istitle())